
sample_units: config/sample_units.txt
resources_config: config/resources.yaml
base_dir: /home/scruz/workflows/ont-common-bean-dna-denovo-assembly/results
bigtmp: /tmp
organism:
  genome_size: 140000000

medaka:
  env: /opt/miniforge/envs/tf2
  model: r1041_e82_400bps_hac_v4.3.0

read_depth_path: ./config/read_depths_purge.txt

nt_db: /opt/InterspecificCommonBeanDenovoGenomeAssembly/5.Others/references/BLAST/nt/nt
taxdump_db: /opt/InterspecificCommonBeanDenovoGenomeAssembly/5.Others/references/taxdump
target_taxa_id: Streptophyta
mpiexec: /home/scruz/software/openmpi/bin/mpiexec
ngsep: /home/scruz/software/NGSEPcore/NGSEPcore_5.0.0.jar
liftOver: /home/scruz/software/liftOver

annotation:
  repeats_env: repeat_modeller
  maker_bin: /home/scruz/software/maker/bin
  maker_env: maker
  augustus_specie_name: "phaseouls_vulgaris_UI-111"
  reference_sequences:
    transcriptome: /home/scruz/workflows/denovo_assembly/resources/Phaseolus_TSA/GAMK01.1.fsa_nt
    proteins: /home/scruz/workflows/denovo_assembly/resources/Phaseolus_proteins/Phaseolus_protein.fa
    uniprot_db: /opt/InterspecificCommonBeanDenovoGenomeAssembly/5.Others/references/Swiss-Prot/uniprot_sprot.fasta

scaffolding:
  linkage_map_markers: /opt/bean_fast/projects/ongoing_projects/allmaps_test/test/resources/BARCPV_SEQS.fa
  linkage_map: /opt/bean_fast/projects/ongoing_projects/allmaps_test/test/resources/gen_pos.txt
  ref_assembly_name: UI-111
  sinteny:
    UI-111:
      peptide_seqs: /opt/InterspecificCommonBeanDenovoGenomeAssembly/5.Others/references/genomes/Pvulgaris/UI-111/v1.1/annotation/PvulgarisUI111_534_v1.1.protein_primaryTranscriptOnly.fa
      prot_sufix: ".1.p"
      gene_annot: /opt/InterspecificCommonBeanDenovoGenomeAssembly/5.Others/references/genomes/Pvulgaris/UI-111/v1.1/annotation/PvulgarisUI111_534_v1.1.gene.sorted.gff3.gz
  dagchainer:
    filter_script: /home/scruz/.conda/envs/dagchainer/bin/accessory_scripts/filter_repetitive_matches.pl
    neighbor_genes_filter: 5
  allmaps_env: ALLMAPS
