###
# Assembly rules
###
flye:
  threads: 80

###
# Polish rules
##
medaka:
  threads: 50

###
# Purge_assembly
###
purge_haplotigs:
  minimap2_threads: 50
  readhist_threads: 50
  purge_threads: 50

###
# Decontamination
###
decontamination:
  blastn_threads: 50
  blastn_mem_mb: 200000

###
# Annotation
###
annotation:
  repeats:
    BuildDatabase_threads: 30
    RepeatMasker_threads: 20
